#### numpy

==>> numarical python

==>> speed & simple to use

==>> Nd - array

In [1]:
# import the numpy  

import numpy

 NumPy’s main object is the homogeneous multidimensional array 
 
 ==>> all elements of an array are same datatype ==> int , float

In [4]:
# array ==> lib ===>> we can create a array with help of ==> array ==> 1D
# numpy ==> lib ==>> we can create a array with help of ==> array  ==> ND
import array
import numpy

In [10]:
# 1D array
arr2 = numpy.array([12,89,45])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[12 89 45]
1
(3,)


In [11]:
# 2D array
arr2 = numpy.array([[12,89,45]])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[12 89 45]]
2
(1, 3)


In [12]:
# 3D array
arr2 = numpy.array([[[12,89,45]]])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[[12 89 45]]]
3
(1, 1, 3)


In [13]:
# 4D array
arr2 = numpy.array([[[[12,89,45]]]])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[[[12 89 45]]]]
4
(1, 1, 1, 3)


In [14]:
# 3D array
arr2 = numpy.array([12,89,45])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

[12 89 45]
1
(3,)
3


In [15]:
# 3D array
arr2 = numpy.array([12,89,45])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[12 89 45]
1
(3,)
3
int32


In [16]:
# 3D array
arr2 = numpy.array([12.23,89,45])
#print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[12.23 89.   45.  ]
1
(3,)
3
float64


In [1]:
# 1D array
import numpy
arr2 = numpy.array([[12.23,89,45],[1,2,3]])
#print(arr1)
print(arr2)
print(arr2.ndim) # 1D
print(arr2.shape) 
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

[[12.23 89.   45.  ]
 [ 1.    2.    3.  ]]
2
(2, 3)
6
float64
8


In [2]:
# arange ---> to create array with seq or AP elements
import numpy
print(numpy.arange(10)) # 0 to 9
print(numpy.arange(3,13))# 3 to 12
print(numpy.arange(3,30,2))# 3,5,7,9,11 ------29

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [5]:
#reshape ===>> modify the shape of the array

import numpy
a = numpy.array([[1,2,3],[4,5,6]]) # (2,3)
print(a)
print(a.shape)
print("**************")
b = a.reshape(3,2)
print(b)
print(b.shape)
print("***********")
c = a.reshape(3,-1)
print(c)
print(c.shape)
print("***********")
d = a.reshape(-1,2)
print(d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
**************
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
***********
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
***********
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [6]:
import numpy as np 
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [9]:
import numpy as np
print(np.zeros((4,5)))
print("*********")
print(np.ones((5,6)))



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
*********
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
# uninitialize data
np.empty( (2,3) )    

array([[12.23, 89.  , 45.  ],
       [ 1.  ,  2.  ,  3.  ]])

In [11]:
import numpy as np
print(np.linspace(4,20,50))

[ 4.          4.32653061  4.65306122  4.97959184  5.30612245  5.63265306
  5.95918367  6.28571429  6.6122449   6.93877551  7.26530612  7.59183673
  7.91836735  8.24489796  8.57142857  8.89795918  9.2244898   9.55102041
  9.87755102 10.20408163 10.53061224 10.85714286 11.18367347 11.51020408
 11.83673469 12.16326531 12.48979592 12.81632653 13.14285714 13.46938776
 13.79591837 14.12244898 14.44897959 14.7755102  15.10204082 15.42857143
 15.75510204 16.08163265 16.40816327 16.73469388 17.06122449 17.3877551
 17.71428571 18.04081633 18.36734694 18.69387755 19.02040816 19.34693878
 19.67346939 20.        ]


In [1]:
# addition 
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = np.array([[18,2,14],[9,8,12]])
print(a)
print(b)
print("*******")
print("addition")
print(a+b)
print("********")
print("subtraction")
print(a-b)
print("*********")
print("multiplication")
print(a*b)

[[ 8  9  7]
 [ 3 10  4]]
[[18  2 14]
 [ 9  8 12]]
*******
addition
[[26 11 21]
 [12 18 16]]
********
subtraction
[[-10   7  -7]
 [ -6   2  -8]]
*********
multiplication
[[144  18  98]
 [ 27  80  48]]


In [2]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
print(a)
print("****")
print("Transpose")
print(a.T)

[[ 8  9  7]
 [ 3 10  4]]
****
Transpose
[[ 8  3]
 [ 9 10]
 [ 7  4]]


In [5]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[2,10,4]])
print(a)
print("****")
print(np.min(a))
print(np.argmin(a))
print("*****")
print(np.max(a))
print(np.argmax(a))

[[ 8  9  7]
 [ 2 10  4]]
****
2
3
*****
10
4


In [6]:
import numpy as np
from math import pi
#2*3 array
a = np.array([[0,pi/6,pi/4],[pi/2,pi/3,pi]])
print(a)
print("****")
print(np.sin(a))

[[0.         0.52359878 0.78539816]
 [1.57079633 1.04719755 3.14159265]]
****
[[0.00000000e+00 5.00000000e-01 7.07106781e-01]
 [1.00000000e+00 8.66025404e-01 1.22464680e-16]]


In [7]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
print(a)
print("****")
print(a ** 3)

[[ 8  9  7]
 [ 3 10  4]]
****
[[ 512  729  343]
 [  27 1000   64]]


In [8]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
print(a)
print("****")
print(a * 3)

[[ 8  9  7]
 [ 3 10  4]]
****
[[24 27 21]
 [ 9 30 12]]


In [11]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
print(a)
print("****")
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis = 1))

[[ 8  9  7]
 [ 3 10  4]]
****
41
[11 19 11]
[24 17]


In [12]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = np.array([[18,2,14],[9,8,12]])

print("****")
print(np.exp(a))
print(a.dot(b))

****
[[2.98095799e+03 8.10308393e+03 1.09663316e+03]
 [2.00855369e+01 2.20264658e+04 5.45981500e+01]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = np.array([[18,2,14],[9,8,12]])
b =b.T
print(a.shape)
print(b.shape)
print("****")
print(np.exp(a))
print(a.dot(b))

(2, 3)
(3, 2)
****
[[2.98095799e+03 8.10308393e+03 1.09663316e+03]
 [2.00855369e+01 2.20264658e+04 5.45981500e+01]]
[[260 228]
 [130 155]]


In [14]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = np.array([[18,2,14],[9,8,12]])

print("****")
print(a< b)

****
[[ True False  True]
 [ True False  True]]


In [16]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = np.array([[8,9,7],[3,10,4]])

print("****")
print(a == b)
print(a is b)

****
[[ True  True  True]
 [ True  True  True]]
False


In [17]:
import numpy as np
#2*3 array
a = np.array([[8,9,7],[3,10,4]])
b = a

print("****")
print(a == b)
print(a is b)

****
[[ True  True  True]
 [ True  True  True]]
True
