# Numpy Basics

Welcome to section of Numpy and Pandas. This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 
 ===>> convenience & speed
 
 ===>> Numpy is much faster than the standard python ways to do computations.
 
 ===>> Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

 ===>> Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 ==>> NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [5]:
# numpy lib ---->> import numpy ---> we have api --> numpy.api()
# list with 10  elements
import numpy
list1 = [12,90.2,34,12.90] # Hetrogenious datatype
arr = numpy.array([12,90.2,34,12.90],dtype = int)# homo
arr1 = numpy.array([12,90.2,34,12.90])# homo
print(list1)
print(arr)
print(arr1)
print(type(list1))
print(type(arr))
print(type(arr1))
print(arr.shape)
print(arr1.shape)
print(arr.ndim)
print(arr1.ndim)

[12, 90.2, 34, 12.9]
[12 90 34 12]
[12.  90.2 34.  12.9]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4,)
(4,)
1
1


In [6]:
import numpy
arr = numpy.array(12,90,23,12)
print(arr)


ValueError: only 2 non-keyword arguments accepted

In [7]:
import numpy
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [11]:
import numpy
arr = numpy.array([12,90,23,12])
print(arr)
print(type(arr))

[12 90 23 12]
<class 'numpy.ndarray'>


In [7]:
import numpy
arr = numpy.array([(12,90,23,12)])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[[12 90 23 12]]
<class 'numpy.ndarray'>
(1, 4)
2


In [3]:
import numpy
arr = numpy.array({12,90,23,12})
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

{90, 12, 23}
<class 'numpy.ndarray'>
()
0


In [2]:
import numpy
arr = numpy.array({12:90,23:12})
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)


{12: 90, 23: 12}
<class 'numpy.ndarray'>
()
0


In [1]:
import numpy
arr = numpy.array("{12,90,23,12}")
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

{12,90,23,12}
<class 'numpy.ndarray'>
()
0


In [28]:
# 1d Array
import numpy
arr = numpy.array([1,2,2])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 2]
1
(3,)


In [26]:
# 2d Array
import numpy
arr = numpy.array([[1,2,2]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 2]]
2
(1, 3)


In [32]:
# 2d Array
import numpy
arr = numpy.array([[1,2,3,1],(4,5,6,2)])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3 1]
 [4 5 6 2]]
2
(2, 4)


In [24]:
# 3d Array
import numpy
arr = numpy.array([[[1,2,3],(4,5,6)],[[4,2,3],(2,8,1)]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[4 2 3]
  [2 8 1]]]
3
(2, 2, 3)


In [13]:
# 3d Array
import numpy
arr = numpy.array([[[1,2,3],(4,5,6)],[[4,2,3],(2,8,1)],[[1,2,3],(4,5,6)]])
print(arr)
print(arr.ndim)
print(arr.shape)
no_of = 1
for var in arr.shape:
    no_of =  no_of * var
print(no_of)

[[[1 2 3]
  [4 5 6]]

 [[4 2 3]
  [2 8 1]]

 [[1 2 3]
  [4 5 6]]]
3
(3, 2, 3)
18


In [2]:
# 4d Array
import numpy
arr = numpy.array([[[[1,2,3]],[[1,2,3]]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3]]

  [[1 2 3]]]]
4
(1, 2, 1, 3)


In [3]:
# list a,b
a = [1,2,3]
b = [4,5,6]
print(a+b)# [5,7,9]

[1, 2, 3, 4, 5, 6]


In [14]:
import numpy
a = [1,2,3]
b = [4,5,6]
a1 = numpy.array(a) 
b1 = numpy.array(b)
print(a)
print(b)
print(a1)
print(b1)
print(a+b)# [1,2,3,4,5,6]
print(a1+b1)
print(len(a1+b1))

[1, 2, 3]
[4, 5, 6]
[1 2 3]
[4 5 6]
[1, 2, 3, 4, 5, 6]
[5 7 9]
3


In [9]:
import numpy
a = [1,2,3]
b = [4,5,6]
a1 = numpy.array(a) 
b1 = numpy.array(b)
print(a)
print(b)
print(a1)
print(b1)
print(a+b)# [1,2,3,4,5,6]
print(a1+b1)

[1, 2, 3]
[4, 5, 6]
[1 2 3]
[4 5 6]
[1, 2, 3, 4, 5, 6]
[5 7 9]


In [9]:
import numpy
a = [1,2,3]
b = [4,5,6]
a1 = numpy.array(a) 
b1 = numpy.array(b)
print(a)
print(b)
print(a1)
print(b1)
#print(a+b)# [1,2,3,4,5,6]
print(a1*b1)

[1, 2, 3]
[4, 5, 6]
[1 2 3]
[4 5 6]
[ 4 10 18]


In [11]:
import numpy
a = [1,2,3]
b = [4,5,6]
a1 = numpy.array(a) 
b1 = numpy.array(b)
print(a1 - b1)


[-3 -3 -3]


# Performance measurement
I mentioned that the key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [17]:
a = [1,2,3]
b = [4,5,6]
import numpy 
a1 = numpy.array([a,b])
print(a1)
print(a1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [12]:
c=range(3) # [0,1,2] ---> [0,1,8]
l =[i**3  for i  in c] # list compre
l

[0, 1, 8]

In [14]:
import numpy as np
c = np.arange(3) # [0,1,2]
d =c ** 3
print(d)

[0 1 8]


In [16]:
c = range(100000)  # [0,1,2,3,4---------99999] ---> [0,1,8,27,64----]
%timeit [i**3 for i in c]


33.9 ms ± 721 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
import numpy as np
c = np.arange(100000)
%timeit c**3


244 µs ± 35 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
a = [1,2,3]
a1 = numpy.array(a)
print(a1)
print(a1[0])
print(a1[1])
del a1[1]
print(a1)

[1 2 3]
1
2


ValueError: cannot delete array elements

Still not convinced? want to see one more intresting example

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [23]:
import numpy as np
print(np.arange(10))
print(np.arange(20))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [24]:
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [26]:
print(np.zeros((4,5)))
print("**************")
print(np.zeros((4,5),int))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
**************
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [27]:
print(np.ones((4,3),int))
print("*****************")
print(np.ones((4,3)))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
*****************
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
print(np.eye(4,dtype=int))
print(np.eye(4))


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
print(np.full((5,4),2))
print(np.full((3,6),4))

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [30]:
np.full((7,6),8.9)

array([[8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9, 8.9]])

In [31]:
import numpy as np
print(np.full((7,6),8.9123, dtype = int))

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [32]:
print(np.diag([7,9,8,1,6,8,5]))

[[7 0 0 0 0 0 0]
 [0 9 0 0 0 0 0]
 [0 0 8 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 6 0 0]
 [0 0 0 0 0 8 0]
 [0 0 0 0 0 0 5]]


In [2]:
v = np.array([1,2])# [1,2]
a =np.tile(v,(4,5)) # stack 4*5 copies of v on top of each other
print(a)
print(a.ndim)
print(a.shape)

[[1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]]
2
(4, 10)


In [3]:
v = np.array([[1,2],[3,4]])
a =np.tile(v,(4,5)) # stack 4*5 copies of v on top of each other
print(a)
print(a.ndim)
print(a.shape)

[[1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]]
2
(8, 10)


In [4]:

# between 0 and 1
np.random.random()

0.28669749339264583

In [5]:
# between 0 and 1
np.random.random((2,3))

array([[0.88061256, 0.06223796, 0.89115546],
       [0.58711721, 0.76818572, 0.05147886]])

In [6]:
# between 0 and 1
np.random.random((2,3,4))

array([[[0.70383565, 0.03558492, 0.51175774, 0.86119384],
        [0.51137383, 0.39796586, 0.27415007, 0.78519234],
        [0.20418789, 0.84421513, 0.0138186 , 0.36017642]],

       [[0.79438402, 0.03905037, 0.28534197, 0.8132648 ],
        [0.37867386, 0.36845821, 0.23463443, 0.24241762],
        [0.2933943 , 0.07107807, 0.22401149, 0.00621425]]])

In [9]:
# so let say I want a random value between 0and 20
20*np.random.random((3,3))

array([[16.40405634, 17.8944089 , 13.2610992 ],
       [14.2898851 ,  4.20472434, 17.81890336],
       [15.70457379,  3.45734688,  7.61131126]])

In [33]:
np.random.choice([1,9,2,4],(2,3))

array([[9, 9, 1],
       [4, 1, 9]])

In [10]:
# so let say I want a random value between 10and 20
10+ 10*np.random.random((4,5))  

array([[17.70583795, 18.21154259, 16.56980391, 14.61463508, 13.62814245],
       [15.52394944, 11.1499111 , 17.12586882, 15.87921032, 11.50796644],
       [12.92039591, 10.49693634, 14.22986128, 14.54949159, 13.00102078],
       [16.30588998, 14.40367303, 12.92267662, 13.66825851, 14.10761136]])

In [39]:
np.random.random([3,3])

array([[0.12134685, 0.21562155, 0.75227312],
       [0.85148308, 0.01789486, 0.34606673],
       [0.59829873, 0.04079237, 0.11344027]])

In [11]:
import numpy as np
# 10 values between 1 and 5
a = np.linspace(1,5,10)
a
print(len(a))
print(a)

10
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [34]:
import numpy as np
# 10 values between 1 and 5
a = np.linspace(1,10,10).reshape(2,5)
a
print(len(a))
print(a)

2
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [21]:
import numpy as np
# 10 values between 1 and 5
a = np.linspace(1,5,10).reshape(-1,5)
a
print(a.ndim)
print(a)

2
[[1.         1.44444444 1.88888889 2.33333333 2.77777778]
 [3.22222222 3.66666667 4.11111111 4.55555556 5.        ]]


In [12]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [22]:
len(a)

2

In [32]:
#memory used by each array element in bytes
print(a.itemsize)
#a.shape
print(a)

print(a.__sizeof__())

for i in a:
    for e in i:
        print(e.itemsize)

8
[[1.         1.44444444 1.88888889 2.33333333 2.77777778]
 [3.22222222 3.66666667 4.11111111 4.55555556 5.        ]]
112
8
8
8
8
8
8
8
8
8
8


In [37]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [35]:
a = np.array([2,4,6,8,10,12,14,16])


In [36]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [37]:
print(a[0])
print(a[1])
print(a[2])
print(a[3])


2
4
6
8


In [48]:
a[[2,4]]

array([ 6, 10])

In [49]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [50]:
a[2:5]

array([ 6,  8, 10])

In [51]:
a[1::2]

array([ 4,  8, 12, 16])

Lets check the same for 2 D array

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a[2,2]

9

In [55]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [58]:
b = a

In [59]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
b[0] = 11

In [61]:
b

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [62]:
# Notice a is also changed
a

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [63]:
np.shares_memory(a,b)

True

In [64]:
a = np.arange(10)

In [65]:
b = a.copy()

In [66]:
b[0] = 11

In [67]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [68]:
np.shares_memory(a,b)

False

In [69]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# More operations

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [3]:
print a
print a.shape
print a.ndim


[[1 2 3]
 [4 5 6]]
(2L, 3L)
2


In [4]:
# matrix transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
b = np.array([[7,8,9],[10,5,12]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b


array([[ 7,  8,  9],
       [10,  5, 12]])

In [8]:
print a == b
print a < b
print a > b
print a != b
print a <= b
print a >= b

[[False False False]
 [False  True False]]
[[ True  True  True]
 [ True False  True]]
[[False False False]
 [False False False]]
[[ True  True  True]
 [ True False  True]]
[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False  True False]]


In [9]:
print a
print b

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10  5 12]]


In [10]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  5, 12]])

In [11]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10,  5, 12]])

# MAthmatical operation

In [13]:
a = np.arange(1,10)
print a

[1 2 3 4 5 6 7 8 9]


In [14]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [16]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [17]:
np.sum(a)

45

In [18]:
a.mean()

5.0

In [22]:
a = np.arange(1,10)

print np.median(a)
a = np.arange(1,11)
print np.median(a)

5.0
5.5


In [23]:
a.std()

2.8722813232690143

In [29]:
a = np.arange(1,10).reshape(3,3)
print a
a = np.arange(1,10).reshape(3,-1)
print a


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
b = np.array([[1,3],[4,5]])
np.linalg.det(b)

-6.999999999999999

In [31]:
np.linalg.det(a)

-9.51619735392994e-16

In [32]:
np.linalg.det(a)
#help(np.linalg.det)

-9.51619735392994e-16

In [33]:
print(np.linalg.inv(a))
#help(np.linalg.inv)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [34]:
np.linalg.eig(a)
#help(np.linalg.eig)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [35]:
print a

b = a.T
print b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [37]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)


In [38]:
np.logical_or(a,b)

array([ True,  True,  True])

In [39]:
np.logical_and(a,b)

array([ True, False, False])

In [40]:
print np.logical_not(a)
print np.logical_xor(a,b)

[False False  True]
[False  True  True]


In [41]:
np.all(a == b)

False

In [42]:
a = np.array([[1,2],[3,4]])

In [43]:
a


array([[1, 2],
       [3, 4]])

In [44]:
a.sum()

10

In [45]:
a.sum(axis=0)

array([4, 6])

In [46]:
a.sum(axis=1)

array([3, 7])

In [47]:
a.max()

4

In [48]:
a.argmax()

3

In [49]:
a=np.array([[1,5,2],[3,1,8]])

In [38]:
print(a.shape)
print(a.ndim)

(2, 5)
2


In [40]:
a = a[:,np.newaxis] # adds a new axis -> 3D
print(a)
print(a.shape)
print(a.ndim)

[[[ 1.  2.  3.  4.  5.]]

 [[ 6.  7.  8.  9. 10.]]]
(2, 1, 5)
3


In [53]:
a

array([[[1, 5, 2]],

       [[3, 1, 8]]])

In [54]:
a = a[:,np.newaxis] # adds a new axis -> 2D
print a
print a.shape
print a.ndim

[[[[1 5 2]]]


 [[[3 1 8]]]]
(2L, 1L, 1L, 3L)
4


In [55]:
np.sort(a)

array([[[[1, 2, 5]]],


       [[[1, 3, 8]]]])

In [56]:
np.argsort(a)
#help(np.argsort)

array([[[[0, 2, 1]]],


       [[[1, 0, 2]]]], dtype=int64)

In [57]:
np.argsort(a)

array([[[[0, 2, 1]]],


       [[[1, 0, 2]]]], dtype=int64)

In [58]:
np.sort(a)

array([[[[1, 2, 5]]],


       [[[1, 3, 8]]]])

In [59]:
a

array([[[[1, 5, 2]]],


       [[[3, 1, 8]]]])

In [60]:
a=np.array([[11,12,14],[9,10,12],[34,45,0]])

In [61]:
a.argmin()

8

In [44]:
import math

A = range(3,30,3)
a = []
for var in A:
    a.append(math.factorial(var))
A = np.array(a)
print(A)

[6 720 362880 479001600 1307674368000 6402373705728000
 51090942171709440000 620448401733239439360000
 10888869450418352160768000000]
